### ISSUE TITLE
Ca un utilizator ANABI, vreau sa vad lista tuturor instantelor de judecata

### ISSUE THREAD

**Issue by vlad2** [code4romania/anabi-gestiune-client#48]
As dori sa pot lista instantele, intr-un tabel asemanator celui care apare cand listez bunurile.

- Tabelul ar trebui sa fie paginat. 

Proprietatile unei instante sunt specificate in 
https://codeforromania.atlassian.net/wiki/spaces/ANABI/pages/267256067/Entit+i

Lista instantelor poate fi gasita aici: 
http://portal.just.ro/SitePages/Instante.aspx

**Comment by vlad2** [comment]
PR-uri:  

Backend: https://github.com/code4romania/anabi-gestiune-api/pull/105
Frontend:  https://github.com/code4romania/anabi-gestiune-client/pull/54

**Comment by vlad2** [comment]
Cosmin Popescu: 

La tabelul "Institutions" ar trebui adaugata coloana:  BusinessId  - integer. 

Si trebuie sterse coloanele:
- CategoryId
- AddressDbId

Si apoi ar trebui modificat endpointul de list institutions sa intoarca BusinessId-ul, nu ID-ul autogenerat. 
Si sa nu mai intoarca categoryId. 

Asa intoarce acum:

```
[
  {
    "id": 1,
    "categoryId": 4,
    "name": "Curtea de Apel Alba Iulia",
    "address": null,
    "contactData": "Some contact here"
  }
]
```

Asa as vrea sa intoarca:

```
[
  {
    "id": 57,    // sau businessId 
    "name": "Curtea de Apel Alba Iulia",
    "contactData": "Some contact here"
  }
]
```

**Comment by cosminpopescu14** [comment]
Sa il am la indemana in Slack :)

**Comment by vlad2** [comment]
Hello,

Am testat popularea institutiilor, si sunt urmatoarele lucruri:

- Cand sterg baza de date, si restartez aplicatia, primesc eroarea:

`
anabi-gestiune-api_1  |       An error occurred seeding the DB.
anabi-gestiune-api_1  | System.IO.FileNotFoundException: Could not find file '/app/..\\institutions.json'.
anabi-gestiune-api_1  | File name: '/app/..\\institutions.json'
anabi-gestiune-api_1  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
anabi-gestiune-api_1  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
anabi-gestiune-api_1  |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
anabi-gestiune-api_1  |    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
anabi-gestiune-api_1  |    at System.IO.File.OpenText(String path)
anabi-gestiune-api_1  |    at Anabi.InstitutionsImporter.InstitutionImporter.Deserialize() in /app/Anabi.InstitutionsImporter/InstitutionImporter.cs:line 18
anabi-gestiune-api_1  |    at Anabi.DataAccess.Ef.DbInitializer.AddInstitutions(AnabiContext context) in /app/Anabi.DataAccess.Ef/DbInitializer.cs:line 34
anabi-gestiune-api_1  |    at Anabi.DataAccess.Ef.DbInitializer.InitializeFullDb(AnabiContext context) in /app/Anabi.DataAccess.Ef/DbInitializer.cs:line 29
anabi-gestiune-api_1  |    at Anabi.Program.Main(String[] args) in /app/Anabi/Program.cs:line 30
anabi-gestiune-api_1  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
`

2. Cand deschid in IDE, nu-mi apare si InstitutionsImporter. Ar trebui sa apara si el (Cred ca nu apare, pentru ca nu e adaugat in Anabi.sln)

3. Pe server nu se copiaza si fisierul institutions.json - poate ar trebui mutat in Anabi.InstitutionsImporter  (si facut punctul 2?)

4. Chiar daca pun eu manual pe server institutions.json, tot nu-l deschide. Cred ca ar trebui folosit Path.combine si unde e apelul de File.OpenText. Ma rog, de fapt, cred ca n-ar trebui folosit "\" in File.OpenText pentru ca \ e separator de directoare doar pe Windows, nu si pe Linux. 


3. Daca totusi deschis InstitutionsImporter intr-un editor oarecare,

**Comment by vlad2** [comment]
M-am uitat pe PR-ul de FE, parea f inofensiv, asa ca i-am dat merge. 

Am facut build nou, insa nu vad nicaieri un ecran cu lista institutiilor.

Redeschidem.

**Comment by RaduCStefanescu** [comment]
@RaduCStefanescu verificat pe serverul de deployment

**Comment by RaduCStefanescu** [comment]
Rezultatul se intoarce ok din baza de date, doar ca datele nu sunt afisate intr-un tabel ci direct JSON dumped in FE. Lasam issue redeschis.

<img width="996" alt="Screenshot 2019-07-27 at 16 26 31" src="https://user-images.githubusercontent.com/15039873/61995009-8207c200-b08b-11e9-94f0-114ab0ac13a6.png">
